# Generated by Django 3.2.5 on 2021-08-23 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=120)),
                ('phone_number', models.IntegerField()),
                ('qualification', models.CharField(max_length=80)),
                ('college', models.CharField(max_length=120)),
                ('percent_or_cgpa', models.IntegerField()),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.job')),
            ],
        ),
    ]
