# Generated by Django 3.2.5 on 2021-08-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dob',
            field=models.CharField(max_length=80),
        ),
    ]
