# Generated by Django 3.2.5 on 2021-08-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeeker', '0004_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('dob', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=120)),
                ('ten_board', models.CharField(max_length=120)),
                ('ten_school', models.CharField(max_length=120)),
                ('ten_percent', models.IntegerField()),
                ('twelve_board', models.CharField(max_length=80)),
                ('twelve_school', models.CharField(max_length=88)),
                ('twelve_percent', models.IntegerField()),
                ('degree_university', models.CharField(max_length=90)),
                ('degree_college', models.CharField(max_length=90)),
                ('degree_cgpa_or_mark', models.IntegerField()),
                ('skills', models.TextField(max_length=200)),
                ('resume', models.FileField(upload_to='files')),
            ],
        ),
    ]
