# Generated by Django 3.2.5 on 2021-08-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('job_title', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_end', models.DateField()),
                ('salary', models.IntegerField(blank=True)),
                ('company_logo', models.ImageField(upload_to='images')),
                ('experience', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('skills', models.TextField(max_length=120)),
                ('desc', models.TextField(max_length=100)),
            ],
        ),
    ]
