# Generated by Django 3.2.5 on 2021-08-23 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='end_end',
            new_name='end_date',
        ),
    ]
