# Generated by Django 3.2.5 on 2021-08-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0003_auto_20210825_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
