# Generated by Django 3.2.5 on 2021-08-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0005_auto_20210826_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(max_length=15),
        ),
    ]
