# Generated by Django 3.2.5 on 2021-08-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0006_alter_job_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='experience',
            field=models.IntegerField(max_length=15),
        ),
    ]
